import { SigninForm } from "@/components/forms/SigninForm";
import { SignupForm } from "@/components/forms/SignupForm";
import { Separator } from "@/components/ui/separator";
import { getSession } from "@/lib/session";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Money App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getSession();
  if (!user) {
    return (
      <html lang="fr">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center items-center h-screen w-full p-20`}
        >
          <div className="grid md:grid-cols-7 w-full h-full ">
            <section className="w-full h-full flex flex-col justify-center items-center max-w-sm mx-auto col-span-3">
              <h2 className="text-2xl font-bold">Se connecter</h2>
              <SigninForm />
            </section>
            <section className="w-full h-full flex justify-center items-center">
              <Separator orientation="vertical" className="hidden md:block" />
            </section>
            <section className="w-full h-full flex flex-col justify-center items-center max-w-sm mx-auto col-span-3">
              <h2 className="text-2xl font-bold">Créer un compte</h2>
              <SignupForm />
            </section>
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
